# Generated by Django 3.0.6 on 2020-07-09 03:10

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_code', models.CharField(default=server.models.create_16_code, max_length=255, unique=True, verbose_name='评论编号')),
                ('user_code', models.CharField(max_length=255, verbose_name='绑定用户编号')),
                ('block_code', models.CharField(default=server.models.create_16_code, max_length=255, unique=True, verbose_name='板块编号')),
                ('content_str', models.TextField(verbose_name='评论内容html')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=server.models.create_16_code, max_length=255, unique=True, verbose_name='用户编号')),
                ('phone_str', models.CharField(max_length=255, unique=True, verbose_name='手机号码')),
                ('nickname_str', models.CharField(default='匿名用户', max_length=16, verbose_name='用户名')),
                ('password_str', models.CharField(max_length=255, verbose_name='密码')),
                ('wx_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信账号')),
                ('avatar_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像地址')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
