# Generated by Django 3.0.6 on 2020-08-18 10:04

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('publish_date', models.DateTimeField(verbose_name='公布时间')),
                ('statement_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=8, verbose_name='所属交易所')),
                ('symbol', models.CharField(max_length=16, verbose_name='股票代码')),
                ('name_cn', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票中文名')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票英文名')),
                ('name_full', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票全称')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='所在地区')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属行业')),
                ('market', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属市场')),
                ('list_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易状态')),
                ('list_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='上市时间')),
                ('delist_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='退市时间')),
            ],
        ),
        migrations.CreateModel(
            name='StockComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_code', models.CharField(default=server.verification.create_16_code, max_length=255, unique=True, verbose_name='评论编号')),
                ('user_code', models.CharField(max_length=255, verbose_name='绑定用户编号')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('content_html', models.CharField(max_length=255, verbose_name='评论内容html路径')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=server.verification.create_16_code, max_length=255, unique=True, verbose_name='用户编号')),
                ('phone_str', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='手机号码')),
                ('nickname_str', models.CharField(default='匿名用户', max_length=16, verbose_name='用户名')),
                ('password_str', models.CharField(max_length=255, verbose_name='密码')),
                ('wx_str', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='微信账号')),
                ('avatar_str', models.CharField(blank=True, default='C:\\Users\\Jackie Li\\Desktop\\gjsicence\\media/avatar/default_avatar.jpg', max_length=255, null=True, verbose_name='头像地址')),
                ('email_str', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户邮箱')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
