# Generated by Django 3.0.6 on 2020-07-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wx_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='微信账号'),
        ),
    ]
