# Generated by Django 3.0.6 on 2020-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='exchange',
            field=models.CharField(default='SZ', max_length=8, verbose_name='所属交易所'),
        ),
    ]
