# Generated by Django 3.0.6 on 2020-08-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200714_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcomments',
            name='block_code',
        ),
        migrations.AddField(
            model_name='stockcomments',
            name='stock_code',
            field=models.CharField(default='123456', max_length=255, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_str',
            field=models.CharField(blank=True, default='C:\\Users\\Jackie Li\\Desktop\\gjsicence\\static/avatar/default_avatar.jpg', max_length=255, null=True, verbose_name='头像地址'),
        ),
    ]
