# Generated by Django 3.0.6 on 2020-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_financialstatement_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='EM_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='权益乘数得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='ROA_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='总资产报酬率得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='ROIC_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='投资回报率得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='cash_flow_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='现金流能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='dept_paying_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
    ]
