# Generated by Django 3.0.6 on 2020-08-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200804_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcomments',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='stockcomments',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
