# Generated by Django 3.0.6 on 2020-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200819_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='arturn_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='assets_to_eqt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='cash_to_liqdebt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='fixed_assets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='ocf_to_debt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='roa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='roic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='偿债能力得分'),
        ),
    ]
