# Generated by Django 3.0.6 on 2020-08-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200804_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcomments',
            old_name='content_str',
            new_name='content_html',
        ),
    ]
