# Generated by Django 3.0.6 on 2020-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200824_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('publish_date', models.DateTimeField(verbose_name='公布时间')),
                ('statement_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('publish_date', models.DateTimeField(verbose_name='公布时间')),
                ('statement_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('publish_date', models.DateTimeField(verbose_name='公布时间')),
                ('statement_content', models.TextField()),
            ],
        ),
    ]
