# Generated by Django 3.0.6 on 2020-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200804_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcomments',
            name='content_html',
            field=models.CharField(max_length=255, verbose_name='评论内容html路径'),
        ),
    ]
