# Generated by Django 3.0.6 on 2020-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_balancestatement_cashflowstatement_incomestatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalytical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('publish_date', models.DateTimeField(verbose_name='公布时间')),
                ('cash_to_assets_ratio', models.CharField(default='123456', max_length=255, verbose_name='现金与现金约当比率')),
                ('crir', models.CharField(default='123456', max_length=255, verbose_name='现金再投资比率')),
                ('cash_adequancy_ratio', models.CharField(default='123456', max_length=255, verbose_name='现金允当比率')),
                ('accounts_receiv_turnover', models.CharField(default='123456', max_length=255, verbose_name='应收账款周转天数')),
                ('gross_profit_margin', models.CharField(default='123456', max_length=255, verbose_name='毛利率')),
                ('cost_rate', models.CharField(default='123456', max_length=255, verbose_name='费用率')),
                ('income_rate', models.CharField(default='123456', max_length=255, verbose_name='净利率')),
                ('roe', models.CharField(default='123456', max_length=255, verbose_name='净资本收益率')),
                ('basic_eps', models.CharField(default='123456', max_length=255, verbose_name='每股收益')),
                ('total_assets_turnover', models.CharField(default='123456', max_length=255, verbose_name='总资本周转率')),
                ('inventories_turnover', models.CharField(default='123456', max_length=255, verbose_name='存货周转天数')),
                ('business_days', models.CharField(default='123456', max_length=255, verbose_name='完整生意周期')),
                ('kmpr', models.CharField(default='123456', max_length=255, verbose_name='缺钱天数')),
                ('debt_to_assets_ratio', models.CharField(default='123456', max_length=255, verbose_name='负债占资产比率')),
                ('longterm_assets_to_fix_assets_ratio', models.CharField(default='123456', max_length=255, verbose_name='长期资金占不动产及设备比率')),
                ('quick_ratio', models.CharField(default='123456', max_length=255, verbose_name='速动比率')),
            ],
        ),
    ]
