# Generated by Django 3.0.6 on 2020-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200804_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcomments',
            name='content_summary',
            field=models.CharField(blank=True, default='...', max_length=255, null=True, verbose_name='评论内容简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_str',
            field=models.CharField(blank=True, default='C:\\Users\\Jackie Li\\Desktop\\gjsicence\\media/avatar/default_avatar.jpg', max_length=255, null=True, verbose_name='头像地址'),
        ),
    ]
