# Generated by Django 3.0.6 on 2020-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_financialanalytical'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialanalytical',
            name='cash_flow_score',
            field=models.CharField(default='123456', max_length=255, verbose_name='cash_flow分数'),
        ),
        migrations.AddField(
            model_name='financialanalytical',
            name='dept_paying_score',
            field=models.CharField(default='123456', max_length=255, verbose_name='dept_paying分数'),
        ),
        migrations.AddField(
            model_name='financialanalytical',
            name='em_score',
            field=models.CharField(default='123456', max_length=255, verbose_name='em分数'),
        ),
        migrations.AddField(
            model_name='financialanalytical',
            name='roa_score',
            field=models.CharField(default='123456', max_length=255, verbose_name='roa分数'),
        ),
        migrations.AddField(
            model_name='financialanalytical',
            name='roic_score',
            field=models.CharField(default='123456', max_length=255, verbose_name='roic分数'),
        ),
    ]
