# Generated by Django 3.0.6 on 2020-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200806_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcomments',
            name='content_summary',
            field=models.BinaryField(blank=True, default=b'...', max_length=255, null=True, verbose_name='评论内容简介'),
        ),
    ]
