# Generated by Django 3.0.6 on 2020-08-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20200806_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcomments',
            name='content_summary',
        ),
    ]
