# Generated by Django 3.0.6 on 2020-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_optionalshares'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalshares',
            name='name_cn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='股票中文名'),
        ),
    ]
