# Generated by Django 3.0.6 on 2020-09-08 04:31

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200908_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalshares',
            name='user_code',
            field=models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='用户编号'),
        ),
    ]
