# Generated by Django 3.0.6 on 2020-10-19 15:25

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20200908_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSharesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='用户编号')),
                ('group_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='分组编号')),
                ('group_name', models.CharField(default='123456', max_length=255, verbose_name='分组名称')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalSharesOprateCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('buy_price', models.FloatField(default=0, verbose_name='成交价格')),
                ('buy_volume', models.IntegerField(verbose_name='持有数量')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
