# Generated by Django 3.0.6 on 2020-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_optionalsharesgroup_optionalsharesopratecover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalsharesopratecover',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='optionalsharesopratecover',
            name='buy_volume',
        ),
        migrations.AddField(
            model_name='optionalshares',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='买入价格'),
        ),
        migrations.AddField(
            model_name='optionalshares',
            name='buy_volume',
            field=models.IntegerField(default=0, verbose_name='持有数量'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='before_volume',
            field=models.IntegerField(default=0, verbose_name='先前持有数量'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='changeType',
            field=models.IntegerField(default=0, verbose_name='更改类型'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='now_volume',
            field=models.IntegerField(default=0, verbose_name='当前持有数量'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='交易价格'),
        ),
    ]
