# Generated by Django 3.0.6 on 2020-11-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20201102_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalshares',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='optionalshares',
            name='buy_volume',
        ),
    ]
