# Generated by Django 3.0.6 on 2020-11-02 14:38

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20201102_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSharesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('name_cn', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票中文名')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('user_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='所属用户编号')),
                ('group_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='所属分组编号')),
                ('sale_price', models.IntegerField(default=0, verbose_name='交易价格')),
                ('now_volume', models.IntegerField(default=0, verbose_name='持有数量')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
