# Generated by Django 3.0.6 on 2020-11-04 12:14

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_optionalsharesitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalsharesitem',
            name='item_code',
            field=models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='自选股编号'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='group_code',
            field=models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='所属分组编号'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='item_code',
            field=models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='所属自选股编号'),
        ),
        migrations.AddField(
            model_name='optionalsharesopratecover',
            name='name_cn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='股票中文名'),
        ),
        migrations.AlterField(
            model_name='optionalsharesitem',
            name='now_volume',
            field=models.FloatField(default=0, verbose_name='持有数量'),
        ),
        migrations.AlterField(
            model_name='optionalsharesitem',
            name='sale_price',
            field=models.FloatField(default=0, verbose_name='交易价格'),
        ),
    ]
