# Generated by Django 3.0.6 on 2020-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20201104_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_tips_active',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否激活邮箱提醒'),
        ),
    ]
