# Generated by Django 3.0.6 on 2020-12-03 14:41

from django.db import migrations, models
import server.verification


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_userprofile_email_tips_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='钱包编号')),
                ('stock_code', models.CharField(default='123456', max_length=255, verbose_name='股票代码')),
                ('name_cn', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票中文名')),
                ('sale_price', models.FloatField(default=0, verbose_name='买入价格')),
                ('now_volume', models.FloatField(default=0, verbose_name='买入数量')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
            ],
        ),
        migrations.CreateModel(
            name='FakeWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='用户编号')),
                ('wallet_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='钱包编号')),
                ('group_name', models.CharField(default='虚拟账号', max_length=255, verbose_name='钱包名称')),
                ('exchange', models.CharField(default='SZ', max_length=8, verbose_name='所属交易所')),
                ('balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='账户余额')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='记录编号')),
                ('wallet_code', models.CharField(default=server.verification.create_16_code, max_length=255, verbose_name='钱包编号')),
                ('item_code', models.CharField(default='000000', max_length=255, verbose_name='交易对象代码')),
                ('item_num', models.IntegerField(verbose_name='交易对象数量')),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易对象价格')),
                ('transaction_type', models.IntegerField(default=0, verbose_name='交易类型')),
                ('transaction_sum', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='交易金额')),
                ('transaction_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易佣金')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_tips_active',
            field=models.IntegerField(default=0, verbose_name='是否激活邮箱提醒'),
        ),
    ]
