# Generated by Django 3.0.6 on 2020-12-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20201203_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakewallet',
            old_name='group_name',
            new_name='wallet_name',
        ),
    ]
