# Generated by Django 3.0.6 on 2020-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20201203_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakestock',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='fakestock',
            name='now_volume',
            field=models.FloatField(default=0, verbose_name='持有数量'),
        ),
    ]
