# Generated by Django 3.0.6 on 2020-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20201203_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_mark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='交易备注'),
        ),
    ]
