# Generated by Django 3.0.6 on 2020-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_transactionrecord_transaction_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakestock',
            name='cost',
            field=models.FloatField(default=0, verbose_name='持仓成本'),
        ),
    ]
